import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Calendar, MapPin, Zap, Clock, CheckCircle2, ArrowRight, RefreshCw, Trophy } from "lucide-react";
import { useTheme } from "../context/ThemeContext";

export default function BuildathonsSection() {
  const { theme } = useTheme();
  const isLight = theme === "light";

  const [realEvents, setRealEvents] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchEvents = async () => {
    setLoading(true);
    try {
      const res = await fetch("https://turingwings-backend.onrender.com/api/events");
      if (res.ok) {
        const data = await res.json();
        setRealEvents(data);
      }
    } catch {
      // Fallback
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvents();
  }, []);

  const fallbackEvents = [
    {
      _id: "1",
      slug: "vibe-coding-sprint-2026",
      title: "Global 48-Hour Vibe Coding Sprint",
      startDate: "August 28, 2026",
      mode: "Online Virtual",
      prizePool: "$10,000 USD",
      tagline: "Transform raw concepts into deployed full-stack web applications in 48 hours using Cursor & Claude 3.7.",
      status: "Registration Open",
      eventType: "Buildathon",
    },
    {
      _id: "2",
      slug: "cyber-shield-masterclass",
      title: "Offensive Cyber Shield Masterclass",
      startDate: "September 05, 2026",
      mode: "Online Virtual",
      prizePool: "$5,000 USD",
      tagline: "Deep-dive into penetration testing AI endpoints, auditing prompt injection vectors, and Zero-Trust shields.",
      status: "Registration Open",
      eventType: "Hackathon",
    },
    {
      _id: "3",
      slug: "agent-swarms-hackathon",
      title: "Autonomous Agent Swarms Hackathon",
      startDate: "September 20, 2026",
      mode: "Hybrid Arena",
      prizePool: "$15,000 USD",
      tagline: "Build multi-agent autonomous teams that write code, execute unit tests, and auto-deploy microservices.",
      status: "Registration Open",
      eventType: "AI Challenge",
    },
  ];

  const displayEvents = realEvents.length > 0 ? realEvents : fallbackEvents;

  return (
    <section
      id="events"
      className="py-16 sm:py-24 relative overflow-hidden select-none bg-white text-slate-900"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-14">
          <span className="px-3 py-1 rounded-full text-xs font-bold uppercase bg-amber-500/20 text-amber-600 border border-amber-500/30">
            DYNAMIC BUILDATHONS DIRECTORY
          </span>
          <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight font-poppins text-slate-900">
            Buildathons, Hackathons & AI Challenges
          </h2>
          <p className="text-base sm:text-lg text-slate-600 font-medium">
            Explore live events generated by Turing Wings Lead Mentors. Select an event to view full details and register.
          </p>
        </div>

        {/* Dynamic Events Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {displayEvents.map((evt) => (
            <motion.div
              key={evt._id || evt.slug}
              whileHover={{ y: -4 }}
              className="p-6 sm:p-8 rounded-3xl bg-white border border-slate-200 shadow-xl flex flex-col justify-between text-left space-y-5"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase bg-slate-900 text-white">
                    {evt.eventType || "Buildathon"}
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase bg-emerald-100 text-emerald-800">
                    {evt.status}
                  </span>
                </div>

                <h3 className="text-xl font-bold font-poppins text-slate-900 leading-snug">
                  {evt.title}
                </h3>
                <p className="text-xs text-slate-600 leading-relaxed">
                  {evt.tagline || evt.description}
                </p>

                <div className="pt-3 border-t border-slate-100 grid grid-cols-2 gap-2 text-[11px] font-mono font-semibold text-slate-500">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5 text-amber-600" />
                    {evt.startDate}
                  </span>
                  <span className="flex items-center gap-1 font-bold text-amber-600">
                    <Trophy className="w-3.5 h-3.5" />
                    {evt.prizePool}
                  </span>
                </div>
              </div>

              <Link
                to={`/event/${evt.slug}`}
                className="w-full py-3 rounded-xl bg-slate-900 hover:bg-amber-600 text-white font-bold text-xs shadow-md transition-all flex items-center justify-center gap-2"
              >
                <span>View Event & Register</span>
                <ArrowRight className="w-4 h-4" />
              </Link>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
